# Generated by Django 3.1.1 on 2020-10-01 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField()),
                ('date_enregistrement', models.DateField()),
                ('commentaire', models.TextField()),
                ('objet', models.TextField()),
                ('situation', models.TextField()),
                ('n_courrier', models.CharField(max_length=2000)),
                ('source', models.CharField(max_length=2000)),
                ('date_reception', models.DateField()),
                ('nature', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
